### ISSUE TITLE
Output path must exists

### ISSUE THREAD

**Issue by tursics** [GovDataOfficial/plantuml-to-ontology#1]
The output folder must exists. Otherwise the error `Error: ENOENT: no such file or directory, open '/Users/thomastursics/github/plantuml-to-ontology/output/analyse.md'`will be shown.

Expected: The output folder will be created if not exists.

Steps to reproduce:
1) delete folder `/output`
2) run the example `node p2o.js examples/dcat-ap-de.plantuml`

**Comment by init-dcat-ap-de** [comment]
Highlighted this fact in README:

> The output directory must already exist, it will not be created by the tool.
